from pathlib import Path
p=Path('work/turnover-monitor-preview.html'); s=p.read_text(encoding='utf-8')
s=s.replace('<option value="risk">Сначала самые срочные</option><option value="stock">Сначала большой остаток</option><option value="name">По названию</option>', '<option value="risk">По общему риску</option><option value="expiry">Сначала ближайший срок</option><option value="turnover">Сначала большая оборачиваемость</option><option value="stock">Сначала большой остаток</option><option value="name">По названию</option>')
old="if(sort.value==='name')a.sort((x,y)=>x.name.localeCompare(y.name,'ru'));else if(sort.value==='stock')a.sort((x,y)=>(y.quantity??y.excessQty??0)-(x.quantity??x.excessQty??0));else a.sort((x,y)=>{const rank=z=>z.kind==='expired'?0:z.kind==='expiring'?1:z.kind==='turnover'&&z.days>180?2:3;return rank(x)-rank(y)||(x.daysLeft??99999)-(y.daysLeft??99999)||(y.excessCost??0)-(x.excessCost??0)});"
new="if(sort.value==='name')a.sort((x,y)=>x.name.localeCompare(y.name,'ru'));else if(sort.value==='stock')a.sort((x,y)=>(y.quantity??y.excessQty??0)-(x.quantity??x.excessQty??0));else if(sort.value==='expiry')a.sort((x,y)=>{const rank=z=>z.kind==='expired'?0:z.kind==='expiring'?1:2;return rank(x)-rank(y)||(x.daysLeft??99999)-(y.daysLeft??99999)});else if(sort.value==='turnover')a.sort((x,y)=>{const rank=z=>z.kind==='turnover'?0:1;return rank(x)-rank(y)||(y.days??-1)-(x.days??-1)});else a.sort((x,y)=>{const rank=z=>z.kind==='expired'?0:z.kind==='expiring'?1:z.kind==='turnover'&&z.days>180?2:3;return rank(x)-rank(y)||(x.daysLeft??99999)-(y.daysLeft??99999)||(y.excessCost??0)-(x.excessCost??0)});"
if old not in s: raise SystemExit('sort block not found')
s=s.replace(old,new)
s=s.replace('Фото пены, герметиков и клеёв взяты из Google-таблицы KRONbuild.', 'Источники: оборачиваемость — «Отчет оборачиваемость товаров.xlsx»; сроки годности и партии — «Отчет по товарам на складах с окончанием срока годности.xlsx»; изображения пены и герметиков/клеёв — страницы «Ассортимент_пены» и «Ассортимент_герметики» Google-таблицы KRONbuild.')
p.write_text(s,encoding='utf-8')
